### ISSUE TITLE
Windows DPI Scaling distorts OpenVR-AdvancedSettings GUI in HMD display

### ISSUE THREAD

**Issue by jpsenior** [matzman666/OpenVR-AdvancedSettings#21]
My main monitor has increased DPI scaling (4K) to 150% (144 DPI I think), and my secondary monitor at 125%.  When viewing the AdvancedSettings GUI some text is truncated, the sliders are off, and it's generally difficult to use.  Some buttons are not clickable under the audio section.

Changing application compatibility  to disable DPI scaling does not work.

I believe this could have something to do with QT's high DPI features: https://doc.qt.io/qt-5/highdpi.html

![image](https://cloud.githubusercontent.com/assets/1619504/21211212/e172a176-c23e-11e6-96bd-87942a32b61e.png)

Example for audio section
![image](https://cloud.githubusercontent.com/assets/1619504/21211231/1462e44c-c23f-11e6-9bea-ada8ecf962f4.png)

My workaround was to set environment variable QT_AUTO_SCREEN_SCALE_FACTOR=1 to forgo QT from trying to scale fonts, pixels, and elements. This worked extremely well.

```
D:\Temp\OpenVR-AdvancedSettings>taskkill /f /im AdvancedSettings.exe
D:\Temp\OpenVR-AdvancedSettings>**set QT_AUTO_SCREEN_SCALE_FACTOR=1**
D:\Temp\OpenVR-AdvancedSettings>AdvancedSettings.exe

```
After the workaround:
![image](https://cloud.githubusercontent.com/assets/1619504/21211461/f50b9164-c240-11e6-92d2-623f9011e483.png)

**Comment by jpsenior** [comment]
To clarify, I'm running this on v2.1 - a fix is stated for high-DPI monitor support, but may not have worked on multi-monitor setups.

**Comment by matzman666** [comment]
Judging from the screenshots you are still running v2.0 (v2.1 comes with a new checkbox design, but your screenshots still show the old checkbox design).

Did you delete all old versions? OpenVR applies the FIFO principle when it comes to application registration. The first application that registers with OpenVR under a certain name will be the one that is started by OpenVR regardless of any later registrations using the same name. Therefore you have to delete (or move) all older version so that OpenVR cannot find them and is forced to start the new version.
