### ISSUE TITLE
OpenVR Advance Settings causes audio issues now with normal Vive games

### ISSUE THREAD

**Issue by lghtanddrk** [matzman666/OpenVR-AdvancedSettings#30]
I installed it to use with Revive touch games.  Currently, you have no way to change the microphone in your settings.  It disregards what's set in SteamVR settings and so you have to change it in Windows Sound Options to match what it sees in OpenVR Advanced Settings to get the microphone working in Revive games.  I understand that,

But, what is really a pain is that I constantly have to change all my settings back in Windows Sound Options, then in SteamVR settings and sometimes even need to reboot when I go back to play a normal Vive game.  If not, my voice is distorted sounding to other players in normal Vive games.  

When I say I sometimes need to reboot it's because if I don't, sometimes the Vive microphone doesn't show back up in SteamVR settings.

Will you be fixing this to read the audio settings that are already in SteamVR so we don't need to change Windows Sound Options?  And/or can you add the ability to change the microphone in OpenVR Advanced Settings?  This would solve a lot of problems.

**Comment by matzman666** [comment]
> Currently, you have no way to change the microphone in your settings. It disregards what's set in SteamVR settings and so you have to change it in Windows Sound Options to match what it sees in OpenVR Advanced Settings to get the microphone working in Revive games.

The microphone set as the default device (that's the one used by Advanced Settings) should be exactly the same as the one selected in SteamVR. That's the whole point of the SteamVR audio settings, when SteamVR starts up it sets the microphone selected there as the default device. When the default device in the Windows settings is not the one set in SteamVR, then it's a SteamVR bug, or some other application has changed the default device (and it cannot be Advanced Settings, because I don't change any default device settings).

Could it be that you have a microphone or a headset that is connected via USB to your PC, and you plug it in after you have started SteamVR? This would explain the issues you are experiencing.

> If not, my voice is distorted sounding to other players in normal Vive games.

I don't change any audio settings besides the volume and the mute setting. So I am wondering how I can cause distorted voices.

> Will you be fixing this to read the audio settings that are already in SteamVR so we don't need to change Windows Sound Options?

As already said, the default device in the Windows settings and the audio device set in SteamVR should be identical. If there aren't then it's caused by something out of my control.

**Comment by lghtanddrk** [comment]
The microphone is not being set exactly as what is in SteamVR settings.  That's the problem.  Before I run  a Revive game and before Ie ver installed OpenVR Advanced Settings, SteamVR Settings matches what's in Windows Sound Options.

What i showing in OpenVR Advanced Settings is not a match to either SteamVR settings or Windows Sound Options.  the only way to get my microphone to work in Revive games is to change the recording device in Windows Sound Options to match OpenVR Advanced Settings.  Then everyone tells me that the sound is muffled or sounds like it's coming through a voice changer.

When I go back to playing normal Vive games using SteamVR settings my microphone does not work.  I have to change it back in Windows Sound Options.  It doesn;t show up in SteamVR settings at all until I completely close out Steam, do a reboot (sometimes) and then the correct microphone reappears for me to select.

I NEVER had theses issues until I installed OpenVR Advanced Settings.  I previously could run Revive with no issues and the sound and everything was fine.

OpenVR Advanced Settings is changing something that it shouldn't.  It's not getting the settings from SteamVR as it should.

I have a webcam that is plugged in all the time.  I have even tried removing it and still have had issues.

**Comment by lghtanddrk** [comment]
I think you can close this.  You sent me a version to try and it seemed to fix the issues for the most part.  Once in a while I still have an issue where I start up SteamVR and the audio settings have changed.  The issue is less frequent now since you sent me the download.

**Comment by lghtanddrk** [comment]
Still have an issue where once in a while the Vive mic gets changes and the speaker output too.  Very rare now.  The issue seems to be more with the mic changing.  I just learned to check and change it each time I start SteamVR now.
