### ISSUE TITLE
Supersampling causing crashes

### ISSUE THREAD

**Issue by darshanshankar** [matzman666/OpenVR-AdvancedSettings#35]
Hello! [Bigscreen](http://store.steampowered.com/app/457550) developer here.

This has become a very popular method of supersampling for SteamVR and VR apps. However, apps like Bigscreen (made with Unity) have our own supersampling settings within the app (`renderScale` in Unity). Our default is 1.75X.

People that set supersampling in Advanced Settings are now crashing within seconds or minutes.

I'd love to discuss some potential solutions. 

I think if users are setting their own supersampling settings in Advanced Settings, we should use that as an override and _not supersample_ in Bigscreen. How should I detect when this occurs?

**Comment by matzman666** [comment]
> People that set supersampling in Advanced Settings are now crashing within seconds or minutes.

1.75 is already a very high supersampling value, and when you combine it with the crazy values other people use in Advanced Settings (some set it to > 2.0) then you run out of memory. When Valve experimented with adaptive rendering in The Lab they maxed out supersampling at 1.4 ([GDC 2016](http://alex.vlachos.com/graphics/Alex_Vlachos_Advanced_VR_Rendering_Performance_GDC2016.pdf), Slide 47) because of memory issues (and above 1.4 you don't see much of a difference anyway). 

In the next version I will most probably change the supersampling slider's upper limit to 2.0 (or maybe even 1.5) as a hint to people that they should scale down their exaggerated supersampling settings.

> I think if users are setting their own supersampling settings in Advanced Settings, we should use that as an override and not supersample in Bigscreen. How should I detect when this occurs?

I don't implement my own supersampling but only use the already available supersampling implementation in SteamVR. It's the same setting you can also set via the steamvr.vrsettings file (the *renderTargetMultiplier* setting). 

OpenVR provides an API that allows to get/set the settings in that settings file. For setting the supersampling value i call `vr::VRSettings()->SetFloat("steamvr", "renderTargetMultiplier", ....)`, and there is also a corresponding get method you can use to read the currently set supersampling value: `vr::VRSettings()->GetFloat("steamvr", "renderTargetMultiplier", ....)` (However, there is one caveat: when a user has modified this value but has not restarted yet, this function will already return the new value, while SteamVR still uses the old one).

> I'd love to discuss some potential solutions.

My suggestion is that you read the current SteamVR supersampling value, and then adjust your supersampling value accordingly. The simplest would be to divide your value through the SteamVR value, this way you always end up with 1.75. And when your value is smaller than the SteamVR value, then don't supersample (or downsample) at all in your application, this way user can still go higher than 1.75 when they want.

**Comment by darshanshankar** [comment]
Minor correction, our default is 1.5X. We allow users to customize render scale from 0.75X up to 2.0X. We noticed crashes and GPU memory issues above 2.0X, and even 2.0X is pretty unstable on some machines.

I've implemented a solution that lets SteamVR settings (or OpenVR Advanced Settings) completely override Bigscreen, and alerts the user of that.

I'll let you know if this continues to crash or cause problems.

Thanks!
