### ISSUE TITLE
SuperSampling of Compositor(SteamVR)

### ISSUE THREAD

**Issue by SharkPolo** [matzman666/OpenVR-AdvancedSettings#8]
Hi.
First thank you for the amazing job.
I had a problem with the SS on the Compositor it get set to 0.1 and I don't know how.
There is another guy that got the same problem.
Also would be very nice if you change the way a option is showed on or off because a lot of people are getting confused with the currently way.
Here a topic on Reddit where you can check what I said.
[Post on Reddit](https://www.reddit.com/r/Vive/comments/5dv4qy/openvr_advanced_settings_i_am_an_idiot_just_check/?st=ivpzg1tc&sh=66838974)

**Comment by DiThi** [comment]
When I updated from 1.x to 2.0 it also went to 0.1 for me. It must be that the application was misreading the setting when it was not stored.

**Comment by DiThi** [comment]
@matzman666 Win8.1

Have you tried this?

- Remove vr settings file
- Use OpenVR-AdvancedSettings 1.x to set some SS value
- Update to 2.0

**Comment by SharkPolo** [comment]
I'm using Windows 10 1607(Anniversary Update) Brazilian Portuguese x64.

**Comment by GiantSox** [comment]
Can also confirm I've seen this issue on Windows 10 (1607), using English (US).

**Comment by DiThi** [comment]
Even though the cause is not known I suggest to work around this by:

- Storing elsewhere your changed compositor SS value.
- If the two values differ, reset to 1.0.

**Comment by matzman666** [comment]
Would be a possible solution, but when another program changes the supersampling value, then it also gets reset to 1.0, which is not a viable solution in my opinion.

I have implemented another possible solution (see commit 4e15b9dea88520e33374508a5043469974be0229). I labeled it "possible" because I still don't know for sure what is causing that issue and cannot reproduce it. 

My theory is that it is related to how Valve changed the handling of default values in OpenVR 1.0.3. Before programmers hat to supply their own default values, but with OpenVR 1.0.3 SteamVR has system-wide default values supplied by Valve themselves (SteamVR includes a file that contains that default value). However, there is no default value for the compositor supersampling value (which would also explain why only the compositor supersampling is affected), and according to the documentation in such a case 0.0 is returned. Normally the non-existing default value for the compositor supersampling does not seem to be a problem as OpenVR usually returns 1.0 even if there is no explicitly defined supersampling value. 

My program regularly asks OpenVR for the current supersampling value (in order to be aware of changes by other programs), and my theory is that in some cases 0.0 gets returned by SteamVR (I suspect when shutting down SteamVR that it might be the case that the subsystem responsible for supersampling has already been shut down when I ask SteamVR for the current supersampling value and since there is no entry in the default value file 0.0 gets returned). The returned value is propagated to the GUI which then says: "Hold on, 0.0 cannot be correct because the minimum value for the supersampling slider is 0.1", and therefore sets supersampling to 0.1.

My solution to this issue is to set supersampling to 1.0 whenever I encounter a supersampling value smaller than 0.01.

**Comment by rxstud2011** [comment]
How do I download this and what do I change?

**Comment by matzman666** [comment]
I [uploaded a new version](https://github.com/matzman666/OpenVR-AdvancedSettings/releases) that contains a possible fix. And in case the fix does not work I added more logging statements to help me determine the cause of the problem. 
Please test it.

**Comment by rxstud2011** [comment]
I will, thank you!
