### ISSUE TITLE
Few extra options for Chaperone, custom center marker, variable grid density

### ISSUE THREAD

**Issue by BOLL7708** [matzman666/OpenVR-AdvancedSettings#88]
Hello! I've been using this to juggle Chaperone settings and tweak the activation distance etc. I have a few ideas on how to expand these features.

* An option for distance-dependent grid density. I'd love if it cycled through "Advanced", "Intermediate" and "Beginner" depending on how close to the wall I am, with "Beginner" being active when closest. I can imagine one third of the distance being used for each density. 
    * To be honest I'd love if Valve would let us customize the appearance completely and/or have dynamic grid density as an option, but my feedback on the SteamVR forums have not been gaining traction in a year or so.
* A customizable play space center marker. I use the current one and I love it, so helpful in games with artificial locomotion, but I would not mind being able to customize it in any way possible to make it more visible and/or personal. Let me provide or swap out a bitmap, vectors in an XML, JSON, svg whichever works best. I tried looking through the resource files to see if I could modify something for this, but I ended up concluding it's likely hard-coded.

Cheers!

**Comment by matzman666** [comment]
> An option for distance-dependent grid density.

That's actually a good idea. For simplicity's sake I would just switch to beginner from whatever you have currently set when you come close enough and then switch back to whatever you had set before, instead of doing a full cycle from advanced to beginner.

> A customizable play space center marker.

I didn't implement the center marker. It's actually part of the chaperone system, but Valve decided for whatever reason to not make it accessible to the end-user. The only thing I did is making the hidden setting configurable for the end-user. When there is a resource file associated with the center marker, then it must be somewhere in the SteamVR installation folder.

**Comment by matzman666** [comment]
The newest version features several chaperone proximity warning methods, one of which is *Switch to Beginner Mode*.
